# Generated by Django 4.2.2 on 2023-06-20 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('precio', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'db_table': 'plan',
            },
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'provincias',
            },
        ),
        migrations.CreateModel(
            name='Terapia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Terapia',
                'verbose_name_plural': 'Terapias',
                'db_table': 'terapia',
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('lastname', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=255)),
                ('provincia', models.CharField(max_length=255)),
                ('sexo', models.CharField(max_length=9)),
                ('dni', models.PositiveIntegerField(unique=True)),
                ('matricula', models.BigIntegerField(unique=True)),
                ('terapiaprofesional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.terapia')),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
                'db_table': 'profesional',
            },
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('lastname', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=255)),
                ('provincia', models.CharField(max_length=255)),
                ('sexo', models.CharField(max_length=9)),
                ('dni', models.PositiveIntegerField(unique=True)),
                ('suscripto', models.BooleanField(default=False)),
                ('planactual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.plan')),
                ('terapiapaciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.terapia')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'paciente',
            },
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=255)),
                ('id_provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.provincias')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'db_table': 'localidad',
            },
        ),
    ]
