# Generated by Django 4.2.1 on 2023-05-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planes',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
