# Generated by Django 4.2.1 on 2023-05-20 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_administrador', models.IntegerField(unique=True)),
                ('nombre_a', models.CharField(max_length=100)),
                ('apellido_a', models.CharField(max_length=100, null=True)),
                ('email_a', models.CharField(max_length=45, unique=True)),
                ('contrasena_a', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TiposDeTerapia',
            fields=[
                ('id_t', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rama', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_u', models.AutoField(primary_key=True, serialize=False)),
                ('provincia', models.CharField(max_length=45)),
                ('localidad', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_paciente', models.IntegerField(unique=True)),
                ('nombre_p', models.CharField(max_length=100)),
                ('apellido_p', models.CharField(max_length=100, null=True)),
                ('email_p', models.CharField(max_length=45, unique=True)),
                ('contrasena_p', models.CharField(max_length=45)),
                ('provincia_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tupsiapp.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_pr', models.IntegerField(unique=True)),
                ('nombre_pr', models.CharField(max_length=100)),
                ('apellido_pr', models.CharField(max_length=100)),
                ('email_pr', models.CharField(max_length=45, null=True)),
                ('contrasena_pr', models.CharField(max_length=8)),
                ('localidad_pr', models.CharField(max_length=45)),
                ('provincia_pr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tupsiapp.ubicacion')),
                ('tipos_de_terapia_pr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tupsiapp.tiposdeterapia')),
            ],
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('precio_plan', models.IntegerField()),
                ('nombre_plan', models.CharField(max_length=50)),
                ('dni_adm_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tupsiapp.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='PagosSuscripciones',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_pago', models.CharField(max_length=20)),
                ('id_plan_p', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_caducidad', models.DateField()),
                ('dni_pac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tupsiapp.usuariopaciente')),
            ],
        ),
    ]
